"""empty message

Revision ID: b430acf17dbd
Revises: 
Create Date: 2022-03-08 14:32:31.981177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b430acf17dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_img_src',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_img_src',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
